package com.cn.drools.examples.helloworld;
import com.cn.drools.pojo.Message
dialect  "java"

rule "Hello World"
    dialect "java"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        System.out.println("------------");
        System.out.println( message );
    modify ( m ) { message = "Goodbye cruel world",
                   status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        Message(status == Message.GOODBYE, message : message )
    then
        System.out.println("===================");
        System.out.println( message );
end
