package com.cn.drools;
import com.cn.drools.pojo.PointDomain
dialect  "java"

//发成退货，扣减10分
rule subBackNumsPoint
    salience 10
    lock-on-active true
    when
        $pointDomain : PointDomain(backNums >= 1)
    then
        $pointDomain.setPoint($pointDomain.getPoint() - 10);
        $pointDomain.recordPointLog($pointDomain.getUserName(), "subBackNumsPoint");
end

//退货金额大于100，扣减100分
rule subBackMoneyPoint
    salience 9
    lock-on-active true
    when
        $pointDomain : PointDomain(backMoney >= 100)
    then
        $pointDomain.setPoint($pointDomain.getPoint() - 100);
        $pointDomain.recordPointLog($pointDomain.getUserName(), "subBackMoneyPoint");
end