package com.cn.drools.examples.state.a;

import com.cn.drools.pojo.State;

declare type State
    @propertyChangeSupport
end

rule "Bootstrap"
  when
    a : State(name == "A", state == NOTRUN )
  then
    System.out.println(a.getName() + " finished" );
    a.setState( com.cn.drools.pojo.State.FINISHED );
end

rule "A to B"
    when
        State(name == "A", state == FINISHED)
        b : State(name == "B", state == NOTRUN)
    then
        System.out.println(b.getName() + " finished");
        b.setState( com.cn.drools.pojo.State.FINISHED );
end

rule "B to C"
    salience 10
  when
    State(name == "B", state == FINISHED )
    c : State(name == "C", state == NOTRUN )
  then
    System.out.println(c.getName() + " finished" );
    c.setState( com.cn.drools.pojo.State.FINISHED );
end

rule "B to D"
  when
    State(name == "B", state == FINISHED )
    d : State(name == "D", state == NOTRUN )
  then
    System.out.println(d.getName() + " finished" );
    d.setState( com.cn.drools.pojo.State.FINISHED );
end
